return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "clangd",
      "css-lsp",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "jedi-language-server",
      "json-lsp",
      "ltex-ls",
      "lua-language-server",
      "marksman",
      "nil",
      "prettier",
      "shellcheck",
      "shfmt",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "taplo",
      "typescript-language-server",
      "typst-lsp",
      "vim-language-server",
      "yaml-language-server",
      "yapf",
      "zls",
    },
    ui = {
      icons = {
        package_pending = " ",
        package_installed = "󰄳 ",
        package_uninstalled = " 󰚌",
      },
    },
  },
}
