return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    highlight = { enable = true, additional_vim_regex_highlighting = { "org", "postcss" } },
    indent = { enable = true },
    context_commentstring = { enable = true, enable_autocmd = false },
    ensure_installed = {
      "bash",
      "bibtex",
      "c",
      "cmake",
      "cpp",
      "css",
      "csv",
      "cue",
      "diff",
      "dockerfile",
      "dot",
      "eex",
      "elixir",
      "erlang",
      "fish",
      "fennel",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "gomod",
      "gowork",
      "gosum",
      "graphql",
      "haskell",
      "haskell_persistent",
      "heex",
      "html",
      "ini",
      "java",
      "javascript",
      "jq",
      "jsdoc",
      "json",
      "json5",
      "jsonc",
      "julia",
      "kdl",
      "latex",
      "llvm",
      "lua",
      "luadoc",
      "make",
      "markdown",
      "markdown_inline",
      "meson",
      "ninja",
      "nix",
      "ocaml",
      "ocaml_interface",
      "ocamllex",
      "org",
      "perl",
      "php",
      "proto",
      "python",
      "r",
      "rasi",
      "ron",
      "rst",
      "ruby",
      "rust",
      "scala",
      "scss",
      "sql",
      "ssh_config",
      "svelte",
      "swift",
      "sxhkdrc",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
      "yuck",
      "zig",
    },
    incremental_selection = {
      enable = true,
      keymaps = {
        init_selection = "<C-space>",
        node_incremental = "<C-space>",
        scope_incremental = "<nop>",
        node_decremental = "<bs>",
      },
    },
  },
}
